[package]
name = "tet2"
version = "0.1.0"
authors = ["melonoidz <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
